### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by chasingkirkjufell** [navcoin/navcoin-wallet-chrome-extension#1]
1. The wallet should stay unlocked after it's closed by the user just like metamask.
2. pressing enter after inputting password does not log in. it should.
3. Wallet tab, there is should be a way to force refresh this page.
4. I would suggest pre-selecting the last used wallet when trying to unlock a wallet.
5. When sending to an invalid address, the error message should be "Invalid address used, please check the address". Currently it's "checksum mismatch".
6. the log in process often fails and leads to me a blank page. it should keep trying and get stuck there.
<img width="293" alt="image" src="https://user-images.githubusercontent.com/38635377/182986148-e95016e8-8f06-4a16-983b-b32e02b43e03.png">
7. After clicking send, there should be a load screen until the transaction is sent. Currently it just goes back to the wallet.

**Comment by chasingkirkjufell** [comment]
8. I think there can be an address book function and it can be called out on the send page to populate the address into the address bar.

**Comment by sakdeniz** [comment]
1. Added feature to ensure that the wallet remembers the last used account and remains unlocked during the active session.
2. Added the feature of logging in with the enter key after entering the password on the login screen.
3. Since subscibe methods are used for actions such as transaction, create collection, mint nft in the wallet, there is no need for a refresh button. The information fields in the wallet update themselves reactively.
4. I will add it as a feature in the next build.
5. An information field has been added to indicate the correctness of the recipient address on the screen, and the ability to check the correctness of the address during the sending process has been added.
6. I've never encountered such a problem before. Please check if the issue persists on version 1.0.3.
7. Added the feature of displaying the modal box on the screen while sending.
8. Added address book feature.

Thanks for your feedback!
